name: Build and Release Plugin

on:
  workflow_run:
    workflows: ["Sync Version from Manifest"]
    types:
      - completed

permissions:
  contents: write

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Read Version
        run: |
          VERSION=$(jq -r .version manifest.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Plugin Zip
        run: |
          zip -r my-todo.zip . \
            -x ".git/*" \
            -x ".github/*" \
            -x "*.md" \
            -x "LICENSE"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          files: my-todo.zip
          # Optionally, add release notes
          # body: "See the [changelog](CHANGELOG.md) for details."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}